export const data = [
  {
    id: 1,
    h3: "Cooking Essentials",
    p: "> Oil ",
    h1: "> Rice ",
    h2: "> Flour",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.postimg.cc%2FRZ275n3f%2Fcabbage.png&w=48&q=75",
  },
  {
    id: 2,
    h3: "Drinks",
    p: "> Tea",
    h1: "> Water ",
    h2: "> Juice",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FhBv30Rt%2Ffrying-pan.png&w=48&q=75",
  },

  {
    id: 3,
    h3: "Milk & Dairy",
    p: ">  Dairiy",
    h1: "> Ice Cream ",
    h2: "> Butter & Ghee",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FdgPzSt7%2Fbagel.png&w=48&q=75",
  },
  {
    id: 4,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FDz8LKDX%2Fsoft-drink.png&w=48&q=75",
  },
  {
    id: 5,
    h3: "Household Tools",
    p: "> Cleaner",
    h1: "> Laundry ",
    h2: "> Air Freshener",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2F181Qpm8%2Fmilk.png&w=48&q=75",
  },
  {
    id: 6,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FDz8LKDX%2Fsoft-drink.png&w=48&q=75",
  },
  {
    id: 7,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 8,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 9,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 10,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 11,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 12,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 13,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 14,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 15,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
  {
    id: 16,
    h3: "Snacks & Instant",
    p: "> Chocalate",
    h1: "> Chips Nuts ",
    h2: "> Conned Food",
    img: "https://kachabazar-store.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2FrdY6zL0%2Fcleaner.png&w=48&q=75",
  },
];
